"""
main.py
-------
Entry point for the Problem2Impact AI microservice.

Run it standalone with:
    pip install -r requirements.txt
    uvicorn main:app --reload --port 8000

Then browse http://localhost:8000/docs for interactive Swagger docs
of every endpoint (auto-generated by FastAPI from the pydantic models
in each route file).

This service is deliberately independent of the Node/Express backend
and the frontend — it only speaks JSON over HTTP and knows nothing
about MongoDB, JWTs, or the browser. The Node backend is the only
thing that talks to this service directly (see each route file's
"HOW NODE/EXPRESS CALLS THIS" docstring for exact integration code).
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

import config
from models.embedding_model import preload
from routes.extract_skills import router as extract_skills_router
from routes.match_teams import router as match_teams_router
from routes.validate_solution import router as validate_solution_router
from routes.detect_duplicate import router as detect_duplicate_router

app = FastAPI(
    title="Problem2Impact AI Service",
    description=(
        "Standalone Python/FastAPI microservice that performs all AI/ML "
        "work for Problem2Impact: skill extraction, collaborator matching, "
        "solution validation, and duplicate detection. Called exclusively "
        "by the Node/Express backend, never directly by the frontend."
    ),
    version="1.0.0",
)

# CORS is only relevant for browser-origin requests (e.g. testing this
# service directly from a local HTML page or the Swagger UI). The real
# Node backend -> AI service traffic is server-to-server and is not
# subject to CORS at all. See config.py for the origin list.
app.add_middleware(
    CORSMiddleware,
    allow_origins=config.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register every AI route. Each router defines its own path
# (e.g. "/extract-skills") so no extra prefix is added here.
app.include_router(extract_skills_router, tags=["Skills"])
app.include_router(match_teams_router, tags=["Matching"])
app.include_router(validate_solution_router, tags=["Validation"])
app.include_router(detect_duplicate_router, tags=["Duplicates"])


@app.on_event("startup")
def on_startup():
    # Load the embedding model once here, so the FIRST real API call
    # doesn't have to pay the ~1-2 second model-loading cost.
    preload()


@app.get("/", tags=["Health"])
def root():
    """Basic liveness check — useful for docker-compose healthchecks."""
    return {"service": "problem2impact-ai-service", "status": "running"}


@app.get("/health", tags=["Health"])
def health():
    """
    Health check the Node backend (or a monitoring tool) can poll
    before assuming the AI service is reachable, e.g. in
    services/aiServiceClient.js you might ping this before showing
    "AI matching temporarily unavailable" instead of a raw 500.
    """
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host=config.HOST, port=config.PORT, reload=True)