const mongoose = require("mongoose");

const CATEGORIES = [
  "Education",
  "Healthcare",
  "Agriculture",
  "Transportation",
  "Industry",
  "Environment",
  "Water & Sanitation",
  "Other",
];

const STATUSES = ["open", "in_progress", "under_review", "solved", "closed"];

const problemSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    description: { type: String, required: true },

    // URLs/paths to uploaded images or documents proving the problem is real
    evidence: { type: [String], default: [] },

    location: { type: String, required: true },
    category: { type: String, enum: CATEGORIES, required: true },

    expectedOutcome: { type: String, required: true },

    // Only present if poster marked "I have domain knowledge"
    hasDomainKnowledge: { type: Boolean, default: false },
    skillsRequired: { type: [String], default: [] },

    budget: { type: Number, default: null }, // optional

    postedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

    status: { type: String, enum: STATUSES, default: "open" },

    // Vector embedding of title+description (+skillsRequired), generated by the AI service,
    // used for collaborator matching and duplicate detection.
    descriptionEmbedding: { type: [Number], default: [] },

    teams: [{ type: mongoose.Schema.Types.ObjectId, ref: "Team" }],
    solutions: [{ type: mongoose.Schema.Types.ObjectId, ref: "Solution" }],

    // Set when a solution has been finalized & funded
    finalizedSolution: { type: mongoose.Schema.Types.ObjectId, ref: "Solution", default: null },
  },
  { timestamps: true }
);

problemSchema.index({ title: "text", description: "text" });
problemSchema.index({ category: 1, location: 1, status: 1 });

module.exports = mongoose.model("Problem", problemSchema);
module.exports.CATEGORIES = CATEGORIES;
module.exports.STATUSES = STATUSES;